package maxpizza.modelo;
// Generated 01-may-2020 17:02:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private Integer idPedido;
     private Persona persona;
     private Date fecha;
     private BigDecimal precioTotal;
     private String formaPago;
     private Set detallepedidos = new HashSet(0);

    public Pedido() {
    }

	
    public Pedido(Persona persona, Date fecha, BigDecimal precioTotal, String formaPago) {
        this.persona = persona;
        this.fecha = fecha;
        this.precioTotal = precioTotal;
        this.formaPago = formaPago;
    }
    public Pedido(Persona persona, Date fecha, BigDecimal precioTotal, String formaPago, Set detallepedidos) {
       this.persona = persona;
       this.fecha = fecha;
       this.precioTotal = precioTotal;
       this.formaPago = formaPago;
       this.detallepedidos = detallepedidos;
    }
   
    public Integer getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(Integer idPedido) {
        this.idPedido = idPedido;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public BigDecimal getPrecioTotal() {
        return this.precioTotal;
    }
    
    public void setPrecioTotal(BigDecimal precioTotal) {
        this.precioTotal = precioTotal;
    }
    public String getFormaPago() {
        return this.formaPago;
    }
    
    public void setFormaPago(String formaPago) {
        this.formaPago = formaPago;
    }
    public Set getDetallepedidos() {
        return this.detallepedidos;
    }
    
    public void setDetallepedidos(Set detallepedidos) {
        this.detallepedidos = detallepedidos;
    }




}


